### ISSUE TITLE
How do I change them? 

### ISSUE THREAD

**Issue by MolkOficial** [Stefan2008Git/FNF-SB-Engine#11]
### Describe your bug/help/problem here.

Hello, I am an Android fnf player who uses the sb engine, I had the previous version and it let me change the keybrinds but in the latest update it doesn't let me. so... how will I play with df jk?? 

### Are you modding a build from source or with Lua?

false

### What is your build target?

Android x86/x64/x32

**Comment by Stefan2008Git** [comment]
Unfortunately i disabled them because no one uses them

**Comment by MolkOficial** [comment]
Now I was going to try a song but the sb engine had crashed

**Comment by Stefan2008Git** [comment]
> Now I was going to try a song but the sb engine had crashed

0.6.3 mods cannot be compatible with 0.7 stuff, so don't play them

**Comment by MolkOficial** [comment]
Ok thanks

**Comment by Stefan2008Git** [comment]
> Ok thanks

Yw, wait for v3.0.0 hotfix update and probably you will play some mods
