### ISSUE TITLE
Hey dude, just a question

### ISSUE THREAD

**Issue by Joalor64GH** [Stefan2008Git/FNF-SB-Engine#12]
### Describe your bug/help/problem here.

So, you tried this PR right?
https://github.com/ShadowMario/FNF-PsychEngine/pull/14362

I used it in my fork, but for some reason, exiting PlayState crashes the game.
I assumed you fixed it on your fork, so how do I fix it?

### Are you modding a build from source or with Lua?

Haxe source code

### What is your build target?

Windows x86/x64/x32

**Comment by Stefan2008Git** [comment]
Use a FlxG.method instead of MusicBeatState because it's deprecreated on Flixel 5.6+ version

**Comment by Joalor64GH** [comment]
That's what I did, but I don't know why it's crashing.

**Comment by Stefan2008Git** [comment]
H

**Comment by Stefan2008Git** [comment]
Then i cannot help 🤷🏻

**Comment by Joalor64GH** [comment]
dang
