### ISSUE TITLE
Help wanted: backporting issue

### ISSUE THREAD

**Issue by Joalor64GH** [Stefan2008Git/FNF-SB-Engine#14]
I tried backporting the new `Bar.hx` class to Joalor64 Engine, which runs on Psych 0.6.3.
But for some reason, the health bar colors are gone and the time bar won't update. Do you think you know how to fix this?

![image](https://github.com/Stefan2008Git/FNF-SB-Engine/assets/99079926/96518567-c690-4664-809a-8ee65b57953e)

**Comment by Stefan2008Git** [comment]
This report is not anything special about SB Engine, so go to Psych server for help or use a PE GitHub repository
