### ISSUE TITLE
I Can't Play Week 6 Because Of Null Object Refusement Please How To Fix It

### ISSUE THREAD

**Issue by Klaskycs** [Stefan2008Git/FNF-SB-Engine#18]
### Describe your bug here.

![Screenshot_٢٠٢٤٠٦٢١_١٦٤٢٢٣](https://github.com/Stefan2008Git/FNF-SB-Engine/assets/161109546/ef2c4908-f357-422d-bdf2-9defa4b58fac)

### Command Prompt/Terminal logs (if existing)

```bash
Pixel Notes Well Crash
```

### Are you modding a build from source or with Lua?

No (I am not using any programming language)

### What is your current build target?

Android x32/x64

### Did you edit anything in this build? If so, mention or summarize your changes.

No I Didn't I Just Play Week 6

**Comment by Stefan2008Git** [comment]
This is already fixed on hotfix version, so you should wait for release

**Comment by AlanGamer23XD** [comment]
Error week ?

**Comment by Klaskycs** [comment]
Yap In Fnf 3.0.0

**Comment by Stefan2008Git** [comment]
> Yap In Fnf 3.0.0

FUCK YOU KASKYCS. YOU ARE SO FUCKING ANNOYING. YOU ARE BLOCKED FROM MY GITHUB REPOSITORY FOR FOREVER

**Comment by Klaskycs** [comment]
Nononono No please I'm sorry forgive me don't ban me 😭

**Comment by CarGamerYoutuber** [comment]
There You Are

**Comment by CarGamerYoutuber** [comment]
Who The Heck Are You

**Comment by moxie-coder** [comment]
stop bumping dead issues
