### ISSUE TITLE
bug with notes

### ISSUE THREAD

**Issue by Hiho2950** [Stefan2008Git/FNF-SB-Engine#18]
### Describe your bug here.

when me or the opponent press a note,some times and when there is some lag the notes go the left or the right then disappears after 1 sec if there is no much of notes and 3 sec if there is a lot of notes and that makes more lags, and i analyse the notes disappears when they are in the screen after going left or right, pls fix that or tell me how to fix it

sorry for the long description but this bug give more lags

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Android

### Did you edit anything in this build? If so, mention or summarize your changes.

yes, i had edit the engine but i didn't edit anything about notes or pressing

**Comment by Stefan2008Git** [comment]
That's not a my problem. You are freaked source code on PlayState for that. I don't have that issue or bug duh

**Comment by Hiho2950** [comment]
i didnt edit the note system and after analysing again this bug only when there is double note or more

**Comment by Stefan2008Git** [comment]
> i didnt edit the note system and after analysing again this bug only when there is double note or more

Buddy, i don't have time to fix everything because i have obligations on real life

**Comment by Hiho2950** [comment]
ok and sorry and thanks for this engine

**Comment by Stefan2008Git** [comment]
> ok and sorry and thanks for this engine

No worries. I'm just here for help. I will fox that what you are saying very soon when i have free time

**Comment by Hiho2950** [comment]
thank you very much, did i need to close the issue

**Comment by Stefan2008Git** [comment]
> thank you very much, did i need to close the issue

If you want

**Comment by Hiho2950** [comment]
ok

**Comment by Hiho2950** [comment]
> > thank you very much, did i need to close the issue
> 
> If you want

i like in your engine the optimizition and i had add more when i had delete all stages

**Comment by Stefan2008Git** [comment]
> > > thank you very much, did i need to close the issue
> > 
> > If you want
> 
> i like in your engine the optimizition and i had add more when i had delete all stages

Deleting ~~stages~~ it's a not good idea because is required for songs

**Comment by Hiho2950** [comment]
i play only mods :sweat_smile:

**Comment by Hiho2950** [comment]
> > > > thank you very much, did i need to close the issue
> > > 
> > > 
> > > If you want
> > 
> > 
> > i like in your engine the optimizition and i had add more when i had delete all stages
> 
> Deleting ~stages~ it's a not good idea because is required for songs

after testing the editorplaystate i got only this issue in the playstate

**Comment by Hiho2950** [comment]
i think the issue is cause of i use 5.2.2 of flixel
