### ISSUE TITLE
Help me

### ISSUE THREAD

**Issue by LDcode17** [Stefan2008Git/FNF-SB-Engine#19]
### Describe your bug here.

I'm tryna compile the source code but I'm getting this error. how do I fix it

### Command Prompt/Terminal logs (if existing)

```bash
source/states/LoadingState.hx:4: characters 8-39 : Type not found : flixel.util.typeLimit.NextState
source/states/LoadingState.hx:8: characters 13-22 : Type not found : NextState
```

### Are you modding a build from source or with Lua?

Source

### What is your current build target?

Windows x64/x32

### Did you edit anything in this build? If so, mention or summarize your changes.

no

**Comment by Stefan2008Git** [comment]
Do you have every library installed on your computer?

**Comment by LDcode17** [comment]
> Do you have every library installed on your computer?

... I think so. just an issue with haxelib git hxCodec https://github.com/polybiusproxy/hxCodec.git

**Comment by LDcode17** [comment]
> > Do you have every library installed on your computer?
> 
> ... I think so. just an issue with haxelib git hxCodec https://github.com/polybiusproxy/hxCodec.git

oh wait I forgot brewscript

**Comment by LDcode17** [comment]
> > > Do you have every library installed on your computer?
> > 
> > 
> > ... I think so. just an issue with haxelib git hxCodec https://github.com/polybiusproxy/hxCodec.git
> 
> oh wait I forgot brewscript

**Comment by LDcode17** [comment]
I forgot brewscript

**Comment by LDcode17** [comment]
I installed it but the bug is still there

**Comment by Stefan2008Git** [comment]
> > Do you have every library installed on your computer?
> 
> ... I think so. just an issue with haxelib git hxCodec https://github.com/polybiusproxy/hxCodec.git

hxCodec is a library for videos, so this library cannot make this error to show

**Comment by Stefan2008Git** [comment]
Uh huh, yeah. You are missing the flixel library, so that's why

**Comment by LDcode17** [comment]
> Uh huh, yeah. You are missing the flixel library, so that's why

thx but what do I have to type to install it?
