### ISSUE TITLE
engine crash

### ISSUE THREAD

**Issue by RedcappedmelonYT** [Stefan2008Git/FNF-SB-Engine#2]
### Describe your bug here.

i literally added everything on the engine, but it kepts crashing!!! why?

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Neko, HashLink, or other build system

### Did you edit anything in this build? If so, mention or summarize your changes.

no

**Comment by Stefan2008Git** [comment]
Wow, wow, wow. Did you just downloaded the 3.0.0 build without my permission?

**Comment by Stefan2008Git** [comment]
> Wow, wow, wow. Did you just downloaded the 3.0.0 build without my permission?

And plus i don't have any fucking clue why is crashing for you. For me is everything fine, but probably is your device.

**Comment by Stefan2008Git** [comment]
Buddy, you wasted my time. Closing the issue during the unanswered question

**Comment by RedcappedmelonYT** [comment]
BRO I DIDN'T ANSWER BECAUSE I SLEPT 💀

**Comment by RedcappedmelonYT** [comment]
also im in android and i made a folder named .sbengine but i did everything, AT ONCE

**Comment by RedcappedmelonYT** [comment]
thats why
