### ISSUE TITLE
Another bug

### ISSUE THREAD

**Issue by LDcode17** [Stefan2008Git/FNF-SB-Engine#20]
### Describe your bug here.

Last time I forgot the flixel library and that fixed the first bug but now this bug is popping up. how do I fix it this time?

### Command Prompt/Terminal logs (if existing)

```bash
source/psychlua/HScript.hx:204: characters 114-119 : Type not found : SCall
```

### Are you modding a build from source or with Lua?

Source

### What is your current build target?

Windows x64/x32

### Did you edit anything in this build? If so, mention or summarize your changes.

no

**Comment by Stefan2008Git** [comment]
This is not a bug, it's just a changed function to TeaCall. Try that

**Comment by LDcode17** [comment]
> This is not a bug, it's just a changed function to TeaCall. Try that

I'm confused what's TeaCall?

**Comment by Stefan2008Git** [comment]
> > This is not a bug, it's just a changed function to TeaCall. Try that
> 
> I'm confused what's TeaCall?

Change the SCall to TeaCall

**Comment by LDcode17** [comment]
> > > This is not a bug, it's just a changed function to TeaCall. Try that
> > 
> > 
> > I'm confused what's TeaCall?
> 
> Change the SCall to TeaCall

**Comment by LDcode17** [comment]
Oh ok

**Comment by LDcode17** [comment]
It's not working

**Comment by Stefan2008Git** [comment]
> It's not working

Hmmm, can i see a HScript for bit
