### ISSUE TITLE
The last bug (hopefully)

### ISSUE THREAD

**Issue by LDcode17** [Stefan2008Git/FNF-SB-Engine#22]
### Describe your bug here.

Well The last 3 were fixed but I'm running into one more bug. Hopefully this is the last one.

### Command Prompt/Terminal logs (if existing)

```bash
C:\Users\ephrem diriba\Desktop\FNF Source Codes\FNF-SB-Engine-main\export\release\windows\obj>setlocal enabledelayedexpansion
Warning: Could not find Visual Studio 2017 VsDevCmd
Missing HXCPP_VARS
Error: Could not automatically setup MSVC
```

### Are you modding a build from source or with Lua?

Source

### What is your current build target?

Windows x64/x32

### Did you edit anything in this build? If so, mention or summarize your changes.

nope.

**Comment by moxie-coder** [comment]
[install visual studio build tools](https://aka.ms/vs/17/release/vs_BuildTools.exe)
![IMG_9638](https://github.com/Stefan2008Git/FNF-SB-Engine/assets/124418090/c942d359-ec6b-4680-8245-666e9c0b2d8b)
