### ISSUE TITLE
Bro can't even charting 💀💀

### ISSUE THREAD

**Issue by MRAdamoC16o** [Stefan2008Git/FNF-SB-Engine#23]
### Describe your bug here.

Dear stefan,

I've tested your engine and found only one bug. I can't even chart my song because the buttons aren't work. If you read this, please fix it. Thank you for reading.

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Android

### Did you edit anything in this build? If so, mention or summarize your changes.

No, I didn't edit anything.

**Comment by MRAdamoC16o** [comment]
P.S:I love your engine because psych engine is too easy to crash.

**Comment by MemeHovy** [comment]
this is likely due to the buttons containing only mobile inputs, but I can readd the mouse inputs

**Comment by Stefan2008Git** [comment]
> ### Describe your bug here.
> Dear stefan,
> 
> I've tested your engine and found only one bug. I can't even chart my song because the buttons aren't work. If you read this, please fix it. Thank you for reading.
> 
> ### Command Prompt/Terminal logs (if existing)
> _No response_
> 
> ### Are you modding a build from source or with Lua?
> Source
> 
> ### What is your build target?
> Android
> 
> ### Did you edit anything in this build? If so, mention or summarize your changes.
> No, I didn't edit anything.

What? How the heck?

**Comment by Stefan2008Git** [comment]
@MRAdamoC16o Can you show a video or i know you for some reason?

**Comment by MRAdamoC16o** [comment]
> @MRAdamoC16o Can you show a video or i know you for some reason?

I was about to show you the bug. Then it fricking fixed itself. Am I got pranked by the engine? Because I installed that version yesterday.

**Comment by MRAdamoC16o** [comment]
Idk how it was fixed.

**Comment by Stefan2008Git** [comment]
> > @MRAdamoC16o Can you show a video or i know you for some reason?
> 
> I was about to show you the bug. Then it fricking fixed itself. Am I got pranked by the engine? Because I installed that version yesterday.

Hmmmm, weirdo. I didn't see that bug before on my Discord server, but yeah. It's a radnomly. It can't be forever

**Comment by MRAdamoC16o** [comment]
I've recorded videos about I'm playing my mods and I've found some bugs (maybe? Idk.) I will share it.

**Comment by MRAdamoC16o** [comment]
![Screenshot_20230817-195056](https://github.com/Stefan2008Git/FNF-SB-Engine/assets/142356047/93337e12-f9aa-4689-9722-a2708c2e5049)

1. "SICK" replaced to "FREAK" (I don't replace it trust me)
2. The song is delayed (happen in that song (glitches) only.)

If you read this please fix it.

**Comment by Stefan2008Git** [comment]
> ![Screenshot_20230817-195056](https://user-images.githubusercontent.com/142356047/261299695-93337e12-f9aa-4689-9722-a2708c2e5049.png)
> 
> 1. "SICK" replaced to "FREAK" (I don't replace it trust me)
> 2. The song is delayed (happen in that song (glitches) only.)
> 
> If you read this please fix it.

No. "Shit" is replaced with "Freak".
Wrong comment. You are just spamming LMAO or something

**Comment by MRAdamoC16o** [comment]
I wish I can share a video but I can't because I don't fricking know

**Comment by MRAdamoC16o** [comment]
I mean when I get perfect, it shows freak instead of sick

**Comment by Stefan2008Git** [comment]
> I wish I can share a video but I can't because I don't fricking know

If you are on Discord server, share on "#sbengine-help" channel on "SB Engine" category

**Comment by MRAdamoC16o** [comment]
Can you give me a link to your discord server?

**Comment by Stefan2008Git** [comment]
> Can you give me a link to your discord server?

https://discord.gg/dEf8aK8ygG
