### ISSUE TITLE
a bunch of issues/bugs i found with 3.0.0h (most recent action build as of when this issue was made)

### ISSUE THREAD

**Issue by JordanSantiagoYT** [Stefan2008Git/FNF-SB-Engine#23]
### Describe your bug here.

this isnt 1, but multiple bugs/issues

note colors options menu: if you change any selected part's color a bunch of times the memory will leak (and the fps will also decrease).
the memory leak happens only if youve started a song before, and it's a minor bug that kinda fixes itself, but the fps decrease happens regardless.

https://github.com/Stefan2008Git/FNF-SB-Engine/assets/61796448/c6e0f337-3d3e-4b14-ba3f-a307418f631c

gameplay options: there are a lot of options that are either useless or should be in visuals & ui instead.
also, one of the options literally does the exact same thing as a gameplay modifier (the option being "die at 0% perent of health", and the gameplay modifier it copies being "practice mode")

visuals & ui options:
rainbow fps doesn't do anything
the "watermark on right down corner" option should at least be renamed to "engine watermark"
the red text on low framerates should be removed and hardcoded.

in the mods menu, the tip telling you to press 7 is cropped off.
![image](https://github.com/Stefan2008Git/FNF-SB-Engine/assets/61796448/ec9e5a0e-92af-4d65-b92c-1988340a4dc0)
if you rebind your controls, they reset every time you close the game but all your other settings remain

the erect difficulty is available for all songs, which shouldn't be the case because not every song has an erect remix. additionally, the difficulty name is misspelled as "errect".
![image](https://github.com/Stefan2008Git/FNF-SB-Engine/assets/61796448/e9655590-00a0-4a45-a983-cbcebd571f9b)

tutorial's jsons have not been updated yet to account for the voices being separated. as a result, playing the song currently only plays an instrumental.
the camera while playing songs is messed up and only works properly if you play on 60FPS.

### Command Prompt/Terminal logs (if existing)

```bash
no crashing from what ive tried, so that's good :)
```

### Are you modding a build from source or with Lua?

Lua

### What is your current build target?

Windows x64/x32

### Did you edit anything in this build? If so, mention or summarize your changes.

no, i used the downloaded build

**Comment by Stefan2008Git** [comment]
1. I don't actually know how to optimize RGB shader code
2. Cannot fix memory leak, so not my fault
3. I don't care tho. My fork, my stuff
4. I added accidentally :/
5. Rainbow FPS is removed during when you have framerate to 30, it will show red text, but if you disable Raibbow FPS, it will not gonna show red text
6. I don't care tho. My fork, my stuff
7. Red FPS text color is useful. You can disable the option to look like the FNF style
8. Becuse Flixel is being dumb or i have to actually fix that on mods menu
9. I odn't actually know how to fix controls issue, so not my fault
10. FUCK IT. I AM NOT STUPID THO
11. Just update it yourself
12. Just disable camera movement because positions are useless

**Comment by Stefan2008Git** [comment]
And who tf allowed you to download build from actions build without my permission @JordanSantiagoYT?

**Comment by JordanSantiagoYT** [comment]
> 1. I don't actually know how to optimize RGB shader code, so not my fault

..you literally made this on psych 0.7.1, cant you just take some code from 0.7.3

> 2. Cannot fix memory leak, so not my fault

The same thing as 1.

> 3. I don't care tho. My fork, my stuff

that's like if i said "JSE is my fork, so I get to add and keep whatever."

> 4. I added accidentally :/

so then remove it.

> 5. Rainbow FPS is removed during when you have framerate to 30, it will show red text, but if you disable Rainbow FPS, it will not gonna show red text

nonono. i searched around the sbe github and it quite literally does nothing

> 6. I don't care tho. My fork, my stuff

copy and pasting a response is crazy.

> 7. Red FPS text color is useful. You can disable the option to look like the FNF style

literally why would i want to disable the red fps to look like normal FNF??

> 8. Becuse Flixel is being dumb or i have to actually fix that on mods menu

you literally just have to move it up by idk, 20? 30?

> 9. I don't actually know how to fix controls issue, so not my fault

i said the same thing about Android when there was the control machine gun issue. the difference is that I actually fixed it.

> 10. FUCK IT. I AM NOT STUPID THO

true, but you let it go unnoticed for about 2 weeks, and only fixed it after the 2nd time i pointed that out

> 11. Just update it yourself

..i don't think it's the best look to leave it up to the users to fix an issue you put in your engine.

> 12. Just disable camera movement because positions are useless

that's completely unrelated to the issue, and even then that doesn't fix it.

> And who tf allowed you to download build from actions build without my permission @JordanSantiagoYT?

dawg.. what do you mean i have to get permission to download your action build??
literally anyone can download it.

**Comment by Stefan2008Git** [comment]
> > 1. I don't actually know how to optimize RGB shader code, so not my fault
> 
> ..you literally made this on psych 0.7.1, cant you just take some code from 0.7.3
> 
> > 2. Cannot fix memory leak, so not my fault
> 
> The same thing as 1.
> 
> > 3. I don't care tho. My fork, my stuff
> 
> that's like if i said "JSE is my fork, so I get to add and keep whatever."
> 
> > 4. I added accidentally :/
> 
> so then remove it.
> 
> > 5. Rainbow FPS is removed during when you have framerate to 30, it will show red text, but if you disable Rainbow FPS, it will not gonna show red text
> 
> nonono. i searched around the sbe github and it quite literally does nothing
> 
> > 6. I don't care tho. My fork, my stuff
> 
> copy and pasting a response is crazy.
> 
> > 7. Red FPS text color is useful. You can disable the option to look like the FNF style
> 
> literally why would i want to disable the red fps to look like normal FNF??
> 
> > 8. Becuse Flixel is being dumb or i have to actually fix that on mods menu
> 
> you literally just have to move it up by idk, 20? 30?
> 
> > 9. I don't actually know how to fix controls issue, so not my fault
> 
> i said the same thing about Android when there was the control machine gun issue. the difference is that I actually fixed it.
> 
> > 10. FUCK IT. I AM NOT STUPID THO
> 
> true, but you let it go unnoticed for about 2 weeks, and only fixed it after the 2nd time i pointed that out
> 
> > 11. Just update it yourself
> 
> ..i don't think it's the best look to leave it up to the users to fix an issue you put in your engine.
> 
> > 12. Just disable camera movement because positions are useless
> 
> that's completely unrelated to the issue, and even then that doesn't fix it.
> 
> > And who tf allowed you to download build from actions build without my permission @JordanSantiagoYT?
> 
> dawg.. what do you mean i have to get permission to download your action build?? literally anyone can download it.

Too late. The build will be released on July 15

**Comment by Stefan2008Git** [comment]
> > > 1. I don't actually know how to optimize RGB shader code, so not my fault
> > 
> > 
> > ..you literally made this on psych 0.7.1, cant you just take some code from 0.7.3
> > > 2. Cannot fix memory leak, so not my fault
> > 
> > 
> > The same thing as 1.
> > > 3. I don't care tho. My fork, my stuff
> > 
> > 
> > that's like if i said "JSE is my fork, so I get to add and keep whatever."
> > > 4. I added accidentally :/
> > 
> > 
> > so then remove it.
> > > 5. Rainbow FPS is removed during when you have framerate to 30, it will show red text, but if you disable Rainbow FPS, it will not gonna show red text
> > 
> > 
> > nonono. i searched around the sbe github and it quite literally does nothing
> > > 6. I don't care tho. My fork, my stuff
> > 
> > 
> > copy and pasting a response is crazy.
> > > 7. Red FPS text color is useful. You can disable the option to look like the FNF style
> > 
> > 
> > literally why would i want to disable the red fps to look like normal FNF??
> > > 8. Becuse Flixel is being dumb or i have to actually fix that on mods menu
> > 
> > 
> > you literally just have to move it up by idk, 20? 30?
> > > 9. I don't actually know how to fix controls issue, so not my fault
> > 
> > 
> > i said the same thing about Android when there was the control machine gun issue. the difference is that I actually fixed it.
> > > 10. FUCK IT. I AM NOT STUPID THO
> > 
> > 
> > true, but you let it go unnoticed for about 2 weeks, and only fixed it after the 2nd time i pointed that out
> > > 11. Just update it yourself
> > 
> > 
> > ..i don't think it's the best look to leave it up to the users to fix an issue you put in your engine.
> > > 12. Just disable camera movement because positions are useless
> > 
> > 
> > that's completely unrelated to the issue, and even then that doesn't fix it.
> > > And who tf allowed you to download build from actions build without my permission @JordanSantiagoYT?
> > 
> > 
> > dawg.. what do you mean i have to get permission to download your action build?? literally anyone can download it.
> 
> Too late. The build will be released on July 15

@moxie-coder Come over please, i just can't

**Comment by moxie-coder** [comment]
what do you want me to do?

**Comment by moxie-coder** [comment]
I mean, okay

**Comment by Stefan2008Git** [comment]
> what do you want me to I dunno, do something because i cannot do anything to fix this stuff what he said and build needs to be released for 4 days

**Comment by moxie-coder** [comment]
> > what do you want me to
> 
> I dunno, do something because i cannot do anything to fix this stuff what he said and build needs to be released for 4 days

I know, I hid that comment because of how aggressive it ass

**Comment by Stefan2008Git** [comment]
> > > what do you want me to
> > 
> > 
> > I dunno, do something because i cannot do anything to fix this stuff what he said and build needs to be released for 4 days
> 
> I know, I hid that comment because of how aggressive it was

I mean it's not that "agressive" how are you saying, but i think that's enough. Someone needs the option to disable red color on FPS when you have low framerate, so someone suggested that idea to add it to my fork. Who actually cares about CPU and RAM usage on note colors menu? That shit is not needed when RGB color is just needed to be modified and Note/StrumNote too.

**Comment by Stefan2008Git** [comment]
> > > > what do you want me to
> > > 
> > > 
> > > I dunno, do something because i cannot do anything to fix this stuff what he said and build needs to be released for 4 days
> > 
> > 
> > I know, I hid that comment because of how aggressive it was
> 
> I mean it's not that "agressive" how are you saying, but i think that's enough. Someone needs the option to disable red color on FPS when you have low framerate, so someone suggested that idea to add it to my fork. Who actually cares about CPU and RAM usage on note colors menu? That shit is not needed when RGB color is just needed to be modified and Note/StrumNote too.

Also, who tf cares tho? Just enable GPU caching if you hate memory leak on my fork
![Screenshot_20240711_062146](https://github.com/Stefan2008Git/FNF-SB-Engine/assets/126715034/c6ddd882-d2ae-4196-a305-be9e108eab13)

**Comment by Stefan2008Git** [comment]
I have to modify Paths and assets folder too to get something, but not right now because it will break everything. I tried once when i ported opponent vocals and it shows the error i am missing the asset path called "`assets/shared/data/funnyTips.txt`"

**Comment by Stefan2008Git** [comment]
![Screenshot_20240711_064441](https://github.com/Stefan2008Git/FNF-SB-Engine/assets/126715034/92c6b7c4-1353-4727-a7cb-4630ceef9321)

Okay, here's why i didn't allowed to download build from actions without my permission because of someone who downloads the build, he will upload it somewhere without my actual acces! So please don't upload build. You are not allowed to do that :(.

**Comment by Stefan2008Git** [comment]
> ![Screenshot_20240711_064441](https://private-user-images.githubusercontent.com/126715034/347682498-92c6b7c4-1353-4727-a7cb-4630ceef9321.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA2NzM4MzAsIm5iZiI6MTcyMDY3MzUzMCwicGF0aCI6Ii8xMjY3MTUwMzQvMzQ3NjgyNDk4LTkyYzZiN2M0LTEzNTMtNDcyNy1hN2NiLTQ2MzBjZWVmOTMyMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcxMVQwNDUyMTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yN2Y3MmM4YTZhY2NhN2E0MTcwYjRkOTgxMDdjNGIyYTRjNGMzYjdmOTBlNTVlOTA2ZGE0MDhlZTg4YzUyYjg1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.WpXOx1t6ew1QyjVdivcKzcBU_f9WCQ-UkenTj1scZmQ)
> 
> Okay, here's why i didn't allowed to download build from actions without my permission because of someone who downloads the build, he will upload it somewhere without my actual acces! So please don't upload build. You are not allowed to do that :(.

# YOU UNDERSTAND NOW WHY YOU NEED A PERMISSION FOR THAT @JordanSantiagoYT

**Comment by JordanSantiagoYT** [comment]
> > ![Screenshot_20240711_064441](https://private-user-images.githubusercontent.com/126715034/347682498-92c6b7c4-1353-4727-a7cb-4630ceef9321.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA2NzM4MzAsIm5iZiI6MTcyMDY3MzUzMCwicGF0aCI6Ii8xMjY3MTUwMzQvMzQ3NjgyNDk4LTkyYzZiN2M0LTEzNTMtNDcyNy1hN2NiLTQ2MzBjZWVmOTMyMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcxMVQwNDUyMTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yN2Y3MmM4YTZhY2NhN2E0MTcwYjRkOTgxMDdjNGIyYTRjNGMzYjdmOTBlNTVlOTA2ZGE0MDhlZTg4YzUyYjg1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.WpXOx1t6ew1QyjVdivcKzcBU_f9WCQ-UkenTj1scZmQ)
> > Okay, here's why i didn't allowed to download build from actions without my permission because of someone who downloads the build, he will upload it somewhere without my actual acces! So please don't upload build. You are not allowed to do that :(.
> 
> # YOU UNDERSTAND NOW WHY YOU NEED A PERMISSION FOR THAT @JordanSantiagoYT

ok, and what if theoretically i DID upload the build somewhere for public access without your permission?

**Comment by Stefan2008Git** [comment]
> > > ![Screenshot_20240711_064441](https://private-user-images.githubusercontent.com/126715034/347682498-92c6b7c4-1353-4727-a7cb-4630ceef9321.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA2NzM4MzAsIm5iZiI6MTcyMDY3MzUzMCwicGF0aCI6Ii8xMjY3MTUwMzQvMzQ3NjgyNDk4LTkyYzZiN2M0LTEzNTMtNDcyNy1hN2NiLTQ2MzBjZWVmOTMyMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcxMVQwNDUyMTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yN2Y3MmM4YTZhY2NhN2E0MTcwYjRkOTgxMDdjNGIyYTRjNGMzYjdmOTBlNTVlOTA2ZGE0MDhlZTg4YzUyYjg1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.WpXOx1t6ew1QyjVdivcKzcBU_f9WCQ-UkenTj1scZmQ)
> > > Okay, here's why i didn't allowed to download build from actions without my permission because of someone who downloads the build, he will upload it somewhere without my actual acces! So please don't upload build. You are not allowed to do that :(.
> > 
> > 
> > # YOU UNDERSTAND NOW WHY YOU NEED A PERMISSION FOR THAT @JordanSantiagoYT
> 
> ok, and what if theoretically i DID upload the build somewhere for public access without your permission?

Serious problems if you do. Some kid just uploaded unfinished 2.9.0 build without my permission directly into Google Drive and i have to ask Google to actually delete the zip file for that reason
