### ISSUE TITLE
Week End 1 Crash 

### ISSUE THREAD

**Issue by CarGamerYoutuber** [Stefan2008Git/FNF-SB-Engine#24]
### Describe your bug here.

Help Week End 1 Crash

### Command Prompt/Terminal logs (if existing)

```bash
Null Object Refusement
```

### Are you modding a build from source or with Lua?

No (I am not using any programming language)

### What is your current build target?

Android x32/x64

### Did you edit anything in this build? If so, mention or summarize your changes.

No I Didn't

**Comment by Stefan2008Git** [comment]
As i said, weekend 1 port is W.I P because the code needs to be edited for Android to work, but I can't do alone everything

**Comment by Stefan2008Git** [comment]
> As i said, weekend 1 port is W.I.P because the code needs to be edited for Android to work, but I can't do alone everything

**Comment by CarGamerYoutuber** [comment]
Oh Sorry Stefan2008 😔😔

**Comment by Stefan2008Git** [comment]
> Oh Sorry Stefan2008 😔😔

You don't need to say sorry to me because i already saw the issue, so you should wait for fully release with working weekend 1 port into Android target

**Comment by CarGamerYoutuber** [comment]
Okay I Well Wait

**Comment by Stefan2008Git** [comment]
> Okay I Well Wait But I Well Be A Beta Tester Of Your Engine And You Credit On Me Next Release

You cannot anymore. There is no left place for that

**Comment by CarGamerYoutuber** [comment]
Why I Want Please 🥺

**Comment by moxie-coder** [comment]
> Why I Want Please 🥺

shut the fuck up

**Comment by Stefan2008Git** [comment]
> > Why I Want Please 🥺
> 
> shut the fuck up

Leave him alone. I just can't deal with this shit anymore and plus kids are everywhere. Remember kids: "Friday Night Funkin' is not for underage people". To solve this problems, simply we can ignore them because they are sometimes annoying to everyone
