### ISSUE TITLE
The sound sometimes gets stuck

### ISSUE THREAD

**Issue by Guillermo4060** [Stefan2008Git/FNF-SB-Engine#25]
### Describe your bug here.

Sometimes the music when playing is heard as if it were cut off and not fluent and in the original psych engine that does not happen and I would like if the problem can be solved since although it is not so annoying the music does not flow

### Command Prompt/Terminal logs (if existing)

```bash
Nothing
```

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Android

### Did you edit anything in this build? If so, mention or summarize your changes.

Nothing

**Comment by MemeHovy** [comment]
@Stefan2008Git you're gonna have to deal with android issues, since I don't got android

**Comment by MemeHovy** [comment]
but also, that could be an issue with your phone

**Comment by Stefan2008Git** [comment]
> ### Describe your bug here.
> Sometimes the music when playing is heard as if it were cut off and not fluent and in the original psych engine that does not happen and I would like if the problem can be solved since although it is not so annoying the music does not flow
> 
> ### Command Prompt/Terminal logs (if existing)
> ```shell
> Nothing
> ```
> 
> ### Are you modding a build from source or with Lua?
> Source
> 
> ### What is your build target?
> Android
> 
> ### Did you edit anything in this build? If so, mention or summarize your changes.
> Nothing

That's not my fault
I tried my best to fix that, but i gives up

**Comment by MemeHovy** [comment]
yea so like I said, likely an issue with your phone, not the game

**Comment by Stefan2008Git** [comment]
> @Stefan2008Git you're gonna have to deal with android issues, since I don't got android

I think @MaysLastPlay10 know everything about Android ports, etc on Haxe, because im so lazybones guy who can't fix that LOL

**Comment by MemeHovy** [comment]
> > @Stefan2008Git you're gonna have to deal with android issues, since I don't got android
> 
> I think @MaysLastPlay10 know everything about Android ports, etc on Haxe, because im so lazybones guy who can't fix that LOL

lol
