### ISSUE TITLE
Update 3.1.0

### ISSUE THREAD

**Issue by Mike20242** [Stefan2008Git/FNF-SB-Engine#25]
### Describe your bug here.

This update is cool and all, but everytime I tried to play a song, the game crashes when opponent sings

### Are you modding a build from source or with Lua?

No (I am not using any programming language)

### What is your current build target?

Android x32/x64

### Did you edit anything in this build? If so, mention or summarize your changes.

I haven't done anything.

**Comment by moxie-coder** [comment]
can you provide crash logs at least?

**Comment by Mike20242** [comment]
> can you provide crash logs at least?

https://github.com/user-attachments/assets/66adde4a-e79a-437c-9392-b32ccbaa9946

**Comment by moxie-coder** [comment]
> > can you provide crash logs at least?
> 
>  mobizen_20240827_150455.1.mp4

seems like a lua issue at the least but I could be wrong, I’m not exactly sure

**Comment by Stefan2008Git** [comment]
> > > can you provide crash logs at least?
> > 
> > 
> > mobizen_20240827_150455.1.mp4
> 
> seems like a lua issue at the least but I could be wrong, I’m not exactly sure

Or it's probably my coding skill issue. I think i screwed something really bad...

**Comment by moxie-coder** [comment]
> > > > can you provide crash logs at least?
> > > 
> > > 
> > > mobizen_20240827_150455.1.mp4
> > 
> > 
> > seems like a lua issue at the least but I could be wrong, I’m not exactly sure
> 
> Or it's probably my coding skill issue. I think i screwed something really bad...

I doubt it was from you, there wasn’t really any indication on what happened

**Comment by moxie-coder** [comment]
> > > > > > can you provide crash logs at least?
> > > > > 
> > > > > 
> > > > > mobizen_20240827_150455.1.mp4
> > > > 
> > > > 
> > > > seems like a lua issue at the least but I could be wrong, I’m not exactly sure
> > > 
> > > 
> > > Or it's probably my coding skill issue. I think i screwed something really bad...
> > 
> > 
> > I doubt it was from you, there wasn’t really any indication on what happened
> 
> Yeah ik.... I just can't everything alone yk?

that's why I try to help

**Comment by Stefan2008Git** [comment]
> > > > > > > can you provide crash logs at least?
> > > > > > 
> > > > > > 
> > > > > > mobizen_20240827_150455.1.mp4
> > > > > 
> > > > > 
> > > > > seems like a lua issue at the least but I could be wrong, I’m not exactly sure
> > > > 
> > > > 
> > > > Or it's probably my coding skill issue. I think i screwed something really bad...
> > > 
> > > 
> > > I doubt it was from you, there wasn’t really any indication on what happened
> > 
> > 
> > Yeah ik.... I just can't everything alone yk?
> 
> that's why I try to help

I am gonna to update the entire source code with latest Psych one
