### ISSUE TITLE
a few issues/bugs i found with the most recent SB Engine action build. (V2 of #23)

### ISSUE THREAD

**Issue by JordanSantiagoYT** [Stefan2008Git/FNF-SB-Engine#26]
### Describe your bug here.

this is a V2 of #23.
before you go and say "Why did you download the action build without my permission?" What are you gonna do, sue me for downloading a PUBLIC action build?

1. "Text Sine" option is misspelled as "Text since"
2. The startup screen is always forced, no matter whether or not the "Startup screen" option is disabled.
3. FPS-based camera speed is still an issue
4. Note hits still count twice
5. There are still some options that aren't useful due to being recreatable with LUA
6. the Note Skins and Note Splashes options are in the Gameplay menu instead of the Visuals menu

### Command Prompt/Terminal logs (if existing)

```bash
nope
```

### Are you modding a build from source or with Lua?

No (I am not using any programming language)

### What is your current build target?

Windows x86/x64/x32

### Did you edit anything in this build? If so, mention or summarize your changes.

nope

**Comment by Stefan2008Git** [comment]
I FUCKING KNOW JORDAN. DON'T YOU SEE I AM LITTLE DEPRESSED BY MY LIFE!?

**Comment by Stefan2008Git** [comment]
> 3\. FPS-based camera speed is still an issue

If you want to solve this shits, then open a pr

**Comment by Stefan2008Git** [comment]
> > 3. FPS-based camera speed is still an issue
> 
> If you want to solve this shits, then open a pr

I am tired with this shits so much

**Comment by cyklusiguess** [comment]
> I FUCKING KNOW JORDAN. DON'T YOU SEE I AM LITTLE DEPRESSED BY MY LIFE!? YOU ARE STARTING TO MAKE ME MAD SO BADLY, I WILL ADD WHATEVER I WANT MO MATTER IF YOU SAW SOMETHING RECREATED FROM SCRIPT

I'M POSTING THIS TO R/COPYPASTA JDSALDALJDKS HELP THIS IS SO FUNNYT

**Comment by cyklusiguess** [comment]
https://www.reddit.com/r/copypasta/comments/1fjd092/i_fucking_know_jordan/

**Comment by Stefan2008Git** [comment]
> > I FUCKING KNOW JORDAN. DON'T YOU SEE I AM LITTLE DEPRESSED BY MY LIFE!? YOU ARE STARTING TO MAKE ME MAD SO BADLY, I WILL ADD WHATEVER I WANT MO MATTER IF YOU SAW SOMETHING RECREATED FROM SCRIPT
> 
> I'M POSTING THIS TO R/COPYPASTA JDSALDALJDKS HELP THIS IS SO FUNNYT

Do whatever you want. Make fun of me, i am fucking tired about bullshits

**Comment by cyklusiguess** [comment]
> > > I FUCKING KNOW JORDAN. DON'T YOU SEE I AM LITTLE DEPRESSED BY MY LIFE!? YOU ARE STARTING TO MAKE ME MAD SO BADLY, I WILL ADD WHATEVER I WANT MO MATTER IF YOU SAW SOMETHING RECREATED FROM SCRIPT
> > 
> > 
> > I'M POSTING THIS TO R/COPYPASTA JDSALDALJDKS HELP THIS IS SO FUNNYT
> 
> Do whatever you want. Make fun of me, i am fucking tired about bullshits

why do you get so mad easily like jordan didn't do anything wrong wtf he's just reporting bugs

**Comment by Stefan2008Git** [comment]
> > > > I FUCKING KNOW JORDAN. DON'T YOU SEE I AM LITTLE DEPRESSED BY MY LIFE!? YOU ARE STARTING TO MAKE ME MAD SO BADLY, I WILL ADD WHATEVER I WANT MO MATTER IF YOU SAW SOMETHING RECREATED FROM SCRIPT
> > > 
> > > 
> > > I'M POSTING THIS TO R/COPYPASTA JDSALDALJDKS HELP THIS IS SO FUNNYT
> > 
> > 
> > Do whatever you want. Make fun of me, i am fucking tired about bullshits
> 
> why do you get so mad easily like jordan didn't do anything wrong wtf he's just reporting bugs

...

Who are you to say about my emotions? You just posted a Reddit post to people make me fun because of this and now you think i am joking? No, i don't. Also the reason why i got mad to Jordan is because i have a anger somethimes and plus he can pull request for fixes and plus you y'all are using his fork instead of mine because he had better shits then mine fork has. I am not feeling good these days because of my life and plus i think i will maybe for seriously discontinue my development because i literally can't everything alone and there is a less 3-4 users who they use my fork because of many bugs and issues.

Have someone asked me how i am these days? No one
Why? Because they probably don't care about my state
