### ISSUE TITLE
bugs and errors

### ISSUE THREAD

**Issue by Guillermo4060** [Stefan2008Git/FNF-SB-Engine#27]
### Describe your bug here.

Hello, I come to report that in the Android version the freeplay z button does not work and in the Chart Mode the left and right buttons do not work, apart from the fact that the sound has a slight lag in the characters' voices

### Command Prompt/Terminal logs (if existing)

```bash
Bug
```

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Android

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by Stefan2008Git** [comment]
You know you are downloaded build without my access or permission?
