### ISSUE TITLE
The game does not open on android

### ISSUE THREAD

**Issue by Guillermo4060** [Stefan2008Git/FNF-SB-Engine#28]
### Describe your bug here.

Hello, again, I don't know if it bothers you but I want to report the error that the game on Android does not open, rather it closes when opened.

### Command Prompt/Terminal logs (if existing)

```bash
No
```

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Android

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by MemeHovy** [comment]
you need to make sure you allowed “Manage all files” for the game, otherwise it will not work

**Comment by Stefan2008Git** [comment]
> you need to make sure you allowed “Manage all files” for the game, otherwise it will not work

Because i can't fix that freaking bug, so that's why @Fearester2008 added that option back

**Comment by Stefan2008Git** [comment]
> ### Describe your bug here.
> Hello, again, I don't know if it bothers you but I want to report the error that the game on Android does not open, rather it closes when opened.
> 
> ### Command Prompt/Terminal logs (if existing)
> ```shell
> No
> ```
> 
> ### Are you modding a build from source or with Lua?
> Source
> 
> ### What is your build target?
> Android
> 
> ### Did you edit anything in this build? If so, mention or summarize your changes.
> No

I freaking hate you so much. You even didn't listened me :(. You made me sadly :( 😔😭. How TF you are even allowed to use my bugged build :(
