### ISSUE TITLE
I keep trying to fix it but I dont know what the issue is

### ISSUE THREAD

**Issue by Themaskedperson** [Stefan2008Git/FNF-SB-Engine#29]
### Describe your bug here.

Ok so I'm using sb engine 2.80 for android I get the mods I wanted and started playing, this never happened before but now it's giving me a message saying
Error! SB Engine v2.8.0

/opt/hostedtoolcache/haxe/4.2.5/x64/ std/cpp/std/sys/FileSystem.hx (Line 101)

backend/WeekData.hx (Line 177)

states/StoryModeState.hx (Line 69)

flixel/FlxGame.hx (Line 642)

flixel/FlxGame.hx (Line 729)

flixel/FlxGame.hx (Line 682)

flixel/FlxGame.hx (Line 550)

openfl/events/EventDispatcher.hx (Line 402)

openfl/display/DisplayObject.hx (Line 1399)
And I don't know how to fix it if you have time could you help me out? 

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Android

### Did you edit anything in this build? If so, mention or summarize your changes.

No I didn't change anything in the build at all

**Comment by Stefan2008Git** [comment]
I think the JSON is probably a invalid or broken for some reason

**Comment by Fearester2008** [comment]
It not invalid JSON, it all not allowed in permissions

**Comment by Stefan2008Git** [comment]
> It not invalid JSON, it all not allowed in permissions

@MemeHovy So how to fix this LOL?

**Comment by MemeHovy** [comment]
> > It not invalid JSON, it all not allowed in permissions
> 
> @MemeHovy So how to fix this LOL?

it's just probably from not allowing file permissions like per usual, but again, I don't have fucking android and I would appreciate it if y'all stopped asking me about it

**Comment by Stefan2008Git** [comment]
> > > It not invalid JSON, it all not allowed in permissions
> > 
> > 
> > @MemeHovy So how to fix this LOL?
> 
> it's just probably from not allowing file permissions like per usual, but again, I don't have fucking android and I would appreciate it if y'all stopped asking me about it

Ahhhh, sorry

**Comment by MemeHovy** [comment]
> > > > It not invalid JSON, it all not allowed in permissions
> > > 
> > > 
> > > @MemeHovy So how to fix this LOL?
> > 
> > 
> > it's just probably from not allowing file permissions like per usual, but again, I don't have fucking android and I would appreciate it if y'all stopped asking me about it
> 
> Ahhhh, sorry

np

**Comment by Stefan2008Git** [comment]
> > > > > It not invalid JSON, it all not allowed in permissions
> > > > 
> > > > 
> > > > @MemeHovy So how to fix this LOL?
> > > 
> > > 
> > > it's just probably from not allowing file permissions like per usual, but again, I don't have fucking android and I would appreciate it if y'all stopped asking me about it
> > 
> > 
> > Ahhhh, sorry
> 
> np

LOL
