### ISSUE TITLE
chart editor won't open

### ISSUE THREAD

**Issue by Vixencool** [Stefan2008Git/FNF-SB-Engine#30]
### Describe your bug here.

when i try to open chart editor i get this error

### Command Prompt/Terminal logs (if existing)

```bash
states/editors/ChartingState.hx (Line 297)
flixel/FlxGame.hx (Line 642)
flixel/FlxGame.hx (Line 729)
flixel/FlxGame.hx (Line 682)
flixel/FlxGame.hx (Line 550)
openfl/events/EventDispatcher.hx (Line 444)
openfl/display/DisplayObject.hx (Line 1400)

Uncaught Error: Null Object Reference
Please report this error to the GitHub page: https://github.com/Stefan2008Git/FNF-SB-Engine

> Crash Handler written by: sqirra-rng
```

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

no i didn't, this is a clean build from gamebanana

**Comment by Stefan2008Git** [comment]
You can't have custom FPS options checked

**Comment by Vixencool** [comment]
i unchecked memory counter and now it works, that's very strange

**Comment by Stefan2008Git** [comment]
> You can't have custom FPS options checked



> i unchecked memory counter and now it works, that's very strange

You can't check/unckeck some options because of position. You need how is correct option setuped because of position, etc.
