### ISSUE TITLE
Noteskins and Notesplashes Skins

### ISSUE THREAD

**Issue by ChumbleDev** [Stefan2008Git/FNF-SB-Engine#31]
### What feature do you want to get added on the SB Engine?

Noteskins and Notesplashes skins because newer psych versions have it

### To test your sight, and reliability, please select the option of what should NOT be requested.

Art sumbition for SB Engine

**Comment by Stefan2008Git** [comment]
How i can redraw basic note and notesplash? I am so bad artist

**Comment by Stefan2008Git** [comment]
> How i can redraw basic note and notesplash? I am so bad artist

Oh, i mean. I can't add new note stuff to engine because it gives many errors as freak

**Comment by ChumbleDev** [comment]
> How i can redraw basic note and notesplash? I am so bad artist

When did i say anything about redrawing?

**Comment by Stefan2008Git** [comment]
> > How i can redraw basic note and notesplash? I am so bad artist
> 
> When did i say anything about redrawing?

I am been confused, so i sayed accidentaly "redraw".

**Comment by ChumbleDev** [comment]
> > > How i can redraw basic note and notesplash? I am so bad artist
> > 
> > 
> > When did i say anything about redrawing?
> 
> I am been confused, so i sayed accidentaly "redraw".

i’m just asking for note and note splash skins (it’s pretty easy to do)
