### ISSUE TITLE
Resync bugs

### ISSUE THREAD

**Issue by JordanSantiagoYT** [Stefan2008Git/FNF-SB-Engine#32]
### Describe your bug here.

so i decided to try running sonorous and found 2 bugs with the engine, which became more apparent when i ran another song without voices (Tutorial):

1. If the game lags, the song will desync from the chart unless the chart says it needs voices
2. If you pause the game, the song will stay muted unless the chart says it needs voices

https://github.com/Stefan2008Git/FNF-SB-Engine/assets/61796448/d30b1684-6718-40e3-b0b4-2494bfd6cf0b

from looking at the source code, it may be because the resync function is skipped if a chart doesn't say the song needs voices.

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

no, i used the downloaded build

**Comment by Stefan2008Git** [comment]
1. Turn off judgement counter, disable some options for that and enable GPU caching.
2. Don't pause and unpause the game because I don't really know how to fix this bug :(. It's not my fault dude, it's a FlxSound issue

**Comment by Stefan2008Git** [comment]
Someone needs to help me to fix that bug because there is no one who csn fix it. I tried everything and my best to fix it, but you know me? I am so bad coder

**Comment by JordanSantiagoYT** [comment]
hmmm...

i might be able to fix it

**Comment by Stefan2008Git** [comment]
> hmmm...
> 
> i might be able to fix it

Then make an pull request please. It's gonna be helpful

**Comment by JordanSantiagoYT** [comment]
alright, im gonna test it first to make sure its working

**Comment by Stefan2008Git** [comment]
> alright, im gonna test it first to make sure its working

I need to warn you:
"Don't even compile the build yet because for some reason i am getting the SScript error that I can't fix it. I tried with @MemeHovy method to add ``#if !macro`` and other methods, but it's an still the same freak (error)

**Comment by JordanSantiagoYT** [comment]
A, i tried compiling and found out what you were talking about 😭

**Comment by Stefan2008Git** [comment]
> A, i tried compiling and found out what you were talking about 😭

Yeah, i am talking about that. You can't compile the build yet because of SScript error. We are trying to add HScript support from 0.7 version somehow
