### ISSUE TITLE
lock the camera

### ISSUE THREAD

**Issue by VeritonR** [Stefan2008Git/FNF-SB-Engine#35]
### What is your question?

The codes "_setProperty('camFollowPos')_"
have they been modified?
I can't lock the camera in a certain position

**Comment by Stefan2008Git** [comment]
Use ``cameraFollowPossition`` i think

**Comment by VeritonR** [comment]
Thanks, it worked

**Comment by Stefan2008Git** [comment]
> Thanks, it worked

Your welcome. Actually some values are changed because of my choice, so that's why
