### ISSUE TITLE
I cant compile the game

### ISSUE THREAD

**Issue by CopyDogOFC** [Stefan2008Git/FNF-SB-Engine#38]
### Describe your bug here.

idk why this thing shows up: source/flixel/sound/FlxSound.hx:598: characters 16-24 : flash.media.SoundChannel has no field __source
source/flixel/sound/FlxSound.hx:602: characters 19-27 : flash.media.SoundChannel has no field __source

### Command Prompt/Terminal logs (if existing)

```bash
source/flixel/sound/FlxSound.hx:598: characters 16-24 : flash.media.SoundChannel has no field __source
source/flixel/sound/FlxSound.hx:602: characters 19-27 : flash.media.SoundChannel has no field __source
```

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by Stefan2008Git** [comment]
Ah, yeah about, error, you need to use an OpenFL library version 9.2.1 and set it up to that version for fix

**Comment by CopyDogOFC** [comment]
> Ah, yeah about that error, you need to use an OpenFL library version 9.2.1 and set it up to that version for fix

Thanks!
