### ISSUE TITLE
idk how to make menu like this

### ISSUE THREAD

**Issue by BambiGaming2022** [Stefan2008Git/FNF-SB-Engine#4]
### Describe your problem here.

i am so dumb here
![dddd](https://user-images.githubusercontent.com/116512242/225947437-6b9c4b20-24eb-4117-b4c3-31cea4d46763.PNG)

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by Stefan2008Git** [comment]
That's so interesting.
