### ISSUE TITLE
Game not opening

### ISSUE THREAD

**Issue by Tyrellwalker1023** [Stefan2008Git/FNF-SB-Engine#6]
### Describe your bug here.

I was trying to open the app, when i clicked allow, the game crashed, i tryed uninstalling but, it did not work, Can you fix this?

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Android

### Did you edit anything in this build? If so, mention or summarize your changes.

No.

**Comment by Tyrellwalker1023** [comment]
when i reinstalled it, still didn't work.

**Comment by Stefan2008Git** [comment]
Version of the engine?
