### ISSUE TITLE
crash w/ "error compiling fragment shader" when playing someone's mod

### ISSUE THREAD

**Issue by rewired-X** [Stefan2008Git/FNF-SB-Engine#6]
### Describe your bug/help/problem here.

I'm asking here since I don't have the slightest idea what it means.
I'm playing "Invalid Data S-side charts" which is built on the SB Engine, and for the second time I get some error saying "Error compiling fragment shader" and a bunch of other stuff, including some ... code?
It's not just on that engine though, and this might be a bit off-topic but when I play Bambi Disposal V9 (OS Engine) I also get the same error.
What is the problem and how can I fix it?
![Screenshot (2577)](https://github.com/Stefan2008Git/FNF-SB-Engine/assets/150751430/1b16de9f-2d18-4fac-bf1c-fb0cf99e6e50)

### Are you modding a build from source or with Lua?

false

### What is your build target?

Windows x86/x64/x32

### Did you edit anything in this build? If so, mention or summarize your changes.

I didn't edit anything, but then again, I'm playing someone else's mod so I don't know what all they adjusted.

**Comment by Stefan2008Git** [comment]
I think your PC can't handle the .frag shader because is required to be edited by someone who knows to code on OpenGL programming language

**Comment by moxie-coder** [comment]
> I think your PC can't handle the .frag shader because is required to be edited by someone who knows to code on OpenGL programming language

👆

**Comment by rewired-X** [comment]
Alright, thanks.
Another question: Can I disable the problematic shaders without causing further problems? Or is it embedded within code and I'm stuck until I find someone that knows what they're doing?

**Comment by Stefan2008Git** [comment]
> Alright, thanks. Another question: Can I disable the problematic shaders without causing further problems? Or is it embedded within code and I'm stuck until I find someone that knows what they're doing?

I don't understand what are you mean, but if you don't want to happens, well, just disable the "Shaders" option and that's all.
