### ISSUE TITLE
[Beta Tester] I am becoming it..

### ISSUE THREAD

**Issue by githubberguy** [Stefan2008Git/FNF-SB-Engine#9]
so as you know you cannot be a beta tester, i will be testing the newest version (with the port of weekend 1 not finished)
on mobile :O

**Comment by Stefan2008Git** [comment]
No, get off. The beta test channel is not opened anymore

**Comment by moxie-coder** [comment]
> so as you know you cannot be a beta tester, i will be testing the newest version (with the port of weekend 1 not finished) on mobile :O

you are not a beta tester unless stated so

**Comment by Stefan2008Git** [comment]
> > so as you know you cannot be a beta tester, i will be testing the newest version (with the port of weekend 1 not finished) on mobile :O
> 
> you are not a beta tester unless stated so

No, people just want a link to upload it without my permission to other people get a unfinished build

**Comment by moxie-coder** [comment]
> > > so as you know you cannot be a beta tester, i will be testing the newest version (with the port of weekend 1 not finished) on mobile :O
> > 
> > 
> > you are not a beta tester unless stated so
> 
> No, people just want a link to upload it without my permission to other people get a unfinished build

that's also kinda my point

**Comment by Stefan2008Git** [comment]
> > > > so as you know you cannot be a beta tester, i will be testing the newest version (with the port of weekend 1 not finished) on mobile :O
> > > 
> > > 
> > > you are not a beta tester unless stated so
> > 
> > 
> > No, people just want a link to upload it without my permission to other people get a unfinished build
> 
> that's also kinda my point

Some kid uploaded on Google Drive and i directly target down the link because of that reason. People are really doesn't understand me i see

**Comment by Stefan2008Git** [comment]
> > > > so as you know you cannot be a beta tester, i will be testing the newest version (with the port of weekend 1 not finished) on mobile :O
> > > 
> > > 
> > > you are not a beta tester unless stated so
> > 
> > 
> > No, people just want a link to upload it without my permission to other people get a unfinished build
> 
> that's also kinda my point

Some kid uploaded on Google Drive and i directly target down the link because of that reason because they think my modified Psych fork can handle many notes.  Exsume me, but how tf i can do that to make it? I am not like the Jordan Santiago. People are really doesn't understand me i see

**Comment by githubberguy** [comment]
well, it wasnt me

**Comment by Stefan2008Git** [comment]
> > No, get off. The beta test channel is not opened anymore
> 
> well bro, its your fault since i have the leak
> 
> so im an inofficial BETA TESTER :o

Fuck you tho. I am sick about motherfuckers and I don't want to add you on credits menu. @moxie-coder, please lock this issue for god sake because i am not feeling good these days

**Comment by Stefan2008Git** [comment]
> > > No, get off. The beta test channel is not opened anymore
> > 
> > 
> > well bro, its your fault since i have the leak
> > so im an inofficial BETA TESTER :o
> 
> Fuck you tho. I am sick about motherfuckers and I don't want to add you on credits menu. @moxie-coder, please lock this issue for god sake because i am not feeling good these days

Nevermind, i did it

**Comment by Stefan2008Git** [comment]
And you are gonna be fucked for seriously @githubberguy. If you gonna try to upload an unfinished link of 3.0.0h, then you are getting what i said
